fastly/compute-sdk-go

- fsthttp/adapter.go
- fsthttp/adapter_test.go
- fsthttp/context.go
This introduces a new `fsthttp.Adapt` function, which converts an `http.Handler` into an `fsthttp.Handler` for use with the
`fsthttp.Serve` function.  This lets us bridge existing code that uses `http.Handler` into the C@E environment.
Any existing `http.Handler` should work and it has been tested with `http.ServeMux`, `gorilla/mux`, and `chi`.  Note, however, that not all fields of the `http.Request` are populated.
The `fsthttp.Request` and `fsthttp.ResponseWriter` types are not exactly the same as their `net/http` counterparts.  In order to make the original `fsthttp` types available inside handlers, new `fsthttp.RequestFromContext` and `fsthttp.ResponseWriterFromContext` functions are provided and can be called on the `http.Request`'s `Context()` method.
Example usage:
```go
func …
```
> fsthttp: add Adapt method for using http.Handlers

- fsthttp/context.go
- fsthttp/transport.go
This allows existing Go code which uses an http.Client to be adapted to
work on Compute@Edge.
This is intended only to adapt existing code.  Using http.Client pulls
in substantially more code than is needed for a simple request,
resulting in slower compile times and larger binaries.  We recommend new
code use the fsthttp.Request type and its Send() method directly
whenever possible.
> add fsthttp.Transport, which is an http.RoundTripper implementation

- .github/actions/bootstrap-integration-test/action.yml
- .github/workflows/integration-tests.yml
- _examples/secret-store/main.go
- _integration_tests/fixtures/secret_store/fastly.toml
- _integration_tests/fixtures/secret_store/main.go
- _integration_tests/sdk-test-config.json
- internal/abi/fastly/hostcalls_guest.go
- internal/abi/fastly/hostcalls_noguest.go
- internal/abi/fastly/types.go
- secretstore/secretstore.go
This adds hostcall and SDK support for the Fastly Secret Store.  An
example is included for usage but the basic idea is:
```go
st, err := secretstore.Open("example_secretstore")
if err != nil {
panic(err)
}
s, err := st.Get("my_secret")
if err != nil {
panic(err)
}
pt, err := s.Plaintext()
if err != nil {
panic(err)
}
fmt.Fprintf(w, "secret value: %q", v)
```
> add Secret Store implementation

- .github/workflows/validate.yml
The latest release of nilness panics when used with Go 1.20.  See
golang/go#58296.  This was fixed, but hasn't been released yet, which
is why we pull from master.
> lint: use nilness from master

- .github/actions/bootstrap-integration-test/action.yml
- .github/actions/install-tinygo/action.yml
- .github/workflows/build-examples.yml
- .github/workflows/integration-tests.yml
- .github/workflows/validate.yml
- _app_template/Makefile
- _integration_tests/fixtures/secret_store/fastly.toml
- _integration_tests/sdk-test-config.json
Drop obsolete `-wasm-abi=generic` flag from TinyGo builds.
Update tooling: 
* Fastly CLI to v8.1.2
* Viceroy to v0.4.0
* TinyGo to v0.27.0.
This also reworks some of the details of CI runs:
* Create an "Install TinyGo" action and use it in workflows to eliminate duplicate manual installation work
* Build integration tests as part of the "Build examples" workflow
* Use a matrix strategy with "Build examples" so it builds with combinations of Go 1.20 and Go 1.19, and TinyGo 0.27.0 and TinyGo 0.26.0, which should help us find build errors due to version incompatibilities.
* Run the integration tests only once, against the latest Go and TinyGo releases.
* Make the "Validate" action run only once in a PR, by setting it to run on all `pull_request` actions and only on `push` to `main`.
> Update CI tooling

- fsthttp/request.go
When the request's ManualFramingMode is false, SendAsyncStreaming streams the request body to the backend using "Transfer-Encoding: chunked".  This is the default behavior we want for requests with a body.  For requests without a body, we want to avoid unnecessary chunked encoding, and have observed servers that error when seeing it in certain contexts.  Calling SendAsync instead causes the entire body to be buffered (in this case, zero bytes) and "Content-Length: 0" to be sent instead.
> use SendAsync, not SendAsyncStreaming, for requests without a body

- _examples/corecache/main.go
- cache/core/core.go
- cache/core/core_test.go
- fsthttp/request.go
- go.mod
- internal/abi/fastly/hostcalls_guest.go
- internal/abi/fastly/hostcalls_noguest.go
- internal/abi/fastly/types.go
- internal/abi/prim/prim.go
- purge/purge.go
The Core Cache API (in the `cache/core` package) exposes the primitive operations required to implement high-performance cache applications with advanced features such as request collapsing, streaming miss, revalidation and surrogate key purging.
While this API contains affordances for some HTTP caching concepts such as Vary headers and stale-while-revalidate, this API is not suitable for HTTP caching out-of-the-box.  Future SDK releases will add a more customizable HTTP Cache API with support for customizable read-through caching, freshness lifetime inference, conditional request evaluation, automatic revalidation, and more.
In the simplest cases, the top-level `Insert` and `Lookup` functions are used for one-off operations on a cached object, and are appropriate when request collapsing …
> Implement Core Cache and Purge APIs

- .gitignore
- _integration_tests/fixtures/kvstore/fastly.toml
- _integration_tests/fixtures/kvstore/main.go
- _integration_tests/sdk-test-config.json
This adds an integration test to show that the happy-paths for kvstore open, insert, and lookup methods work as expected
> test: add kvstore basic test app

- fsthttp/backend.go
The error names are longish, happy to go for something shorter.
We should probably add other errors, e.g., https://docs.rs/fastly/0.9.4/src/fastly/backend/builder.rs.html#231, but I'd leave that for another PR.
> Improve errors on failure

- CHANGELOG.md
- _examples/simplecache/main.go
- cache/core/core.go
- cache/simple/simple.go
This introduces a new Simple Cache API in the `cache/simple` package.
This provides a simpler interface to inserting and retrieving entries from Fastly's cache: `Get`, `GetOrSet`, and `Purge`.
Cache operations are local to the Fastly POP serving the request, but purges can also be performed globally.
> Implement Simple Cache API

- fsthttp/backend.go
- internal/abi/fastly/hostcalls_guest.go
- internal/abi/fastly/hostcalls_noguest.go
- internal/abi/fastly/types.go
Replace `backend.IsHealthy()` with `backend.Health()`, because it returns an
enum of 3 states (unknown, healthy, unhealthy) and not a bool.
When populating the backend, the runtime will return `FastlyStatusNone`
if a value isn't set.  This isn't an error, so we should ignore it.
Similarly, the Viceroy environment will return `FastlyStatusUnsupported`
for some unsupported fields and we should ignore them too.
The exported names for getting SSL min/max versions were copypasta'd and
returned the wrong values.
Fixes #65.
> fix a handful of backend bugs

- fsthttp/request.go
- internal/abi/fastly/types.go
We created this error for the dynamic backend work, but it applies to
Send() as well.
Because Send wraps the underlying FastlyStatus error, we need to support
unwrapping in IsFastlyError.
> return nicer ErrBackendNotFound when sending to unknown backend

- .gitignore
- README.md
- _examples/README.md
- _examples/add-or-remove-cookies/fastly.toml
- _examples/corecache/fastly.toml
- _examples/geodata/fastly.toml
- _examples/hello-world/fastly.toml
- _examples/kvstore/fastly.toml
- _examples/limits/fastly.toml
- _examples/limits/main.go
- _examples/logging-and-env/fastly.toml
- _examples/middlewares/fastly.toml
- _examples/multiple-goroutines/fastly.toml
- _examples/parallel-requests/fastly.toml
- _examples/parallel-requests/main.go
- _examples/print-request/fastly.toml
- _examples/proxy-request-framing/fastly.toml
- _examples/proxy-request-framing/main.go
- _examples/proxy-request/fastly.toml
- _examples/proxy-request/main.go
- _examples/secret-store/fastly.toml
- _examples/set-cookie/fastly.toml
- _examples/set-google-analytics/fastly.toml
- _examples/simplecache/fastly.toml
- _examples/stream-response/fastly.toml
- _examples/with-timeout/fastly.toml
- _examples/with-timeout/main.go
This mades it so you can run `fastly compute serve` in each example
directory to test them out locally.
Fixes #67
> _examples: add fastly.toml for each example, plus a README.

- integration_tests/secret_store/main_test.go
- internal/abi/fastly/hostcalls_guest.go
- internal/abi/fastly/hostcalls_noguest.go
- secretstore/secretstore.go
This creates a `secretstore.Secret` instance from a byte slice.  This is
for situations in which an API requires a `Secret` but you cannot (for
whatever reason) use a `Store` to store them.
> secretstore: add SecretFromBytes

- fsthttp/response.go
- fsttest/recorder.go
- integration_tests/request_upstream/main_test.go
This mirrors the Response::append_body method in the Rust SDK: https://docs.rs/fastly/0.9.5/fastly/http/struct.Response.html#method.append_body
> Add Append method to ResponseWriter

- cache/core/core.go
- configstore/configstore.go
- fsthttp/backend.go
- kvstore/kvstore.go
- secretstore/secretstore.go
This PR improves the error handling in a handful of places.
It adds contextual errors to the `kvstore` package, so we're not returning user unfriendly raw `FastlyStatus` error codes.
It also adds an unexpected error sentinel to most packages if they don't already have them, and adds the `FastlyStatus` code to them for easier debugging.
Fixes #16, #23, and #83.
> Improve error handling

- .github/workflows/build-examples.yml
- .github/workflows/integration-tests.yml
- CHANGELOG.md
Update Viceroy to 0.9.2.
Test builds with newest and oldest supported combinations of Go and
TinyGo.  Currently this is 1.19.x with 0.28.1 and 1.21.x with 0.30.0.
> .github: update CI versions

- CHANGELOG.md
The formatting is important, as we autogenerate the changelog on https://developer.fastly.com/reference/changes/go-sdk/ from these.
> fix Changelog format

- .github/workflows/integration-tests.yml
- CHANGELOG.md
- _examples/device-detection/fastly.toml
- _examples/device-detection/main.go
- device/device_detection.go
- integration_tests/device_detection/fastly.toml
- integration_tests/device_detection/main_test.go
- internal/abi/fastly/hostcalls_guest.go
- internal/abi/fastly/hostcalls_noguest.go
Calling `device.Lookup()` returns a `Device` struct with accessor
methods to get information on the user agent such as name/brand/model as
well as booleans for common device types.
Based on the API in the [Rust SDK](https://docs.rs/fastly/latest/fastly/device_detection/index.html) and our VCL variables.
> add a new `device` package for device detection

- .github/workflows/build-examples.yml
- .github/workflows/integration-tests.yml
- fsthttp/request.go
- integration_tests/request_upstream/fastly.toml
- integration_tests/request_upstream/main_test.go
`bytes.Buffer`, `bytes.Reader`, and `strings.Reader` are all `io.Reader`
implementations on an in-memory buffer.  Their sizes are known ahead of
time, and these types tend to be used for small payloads.  We can send
these payloads with a `Content-Length` rather than using chunked
encoding by sending them with `SendAsync` rather than
`SendAsyncStreaming`.
> don't stream certain in-memory io.Readers

- .github/workflows/build-examples.yml
- .github/workflows/integration-tests.yml
- fsthttp/request.go
I started doing this to bring #44 up-to-date to decide if we really want to do it.  I found the inconsistency on whether to use the struct members confusing, so I removed them.  Another approach would be to go the other way and lean into tracking that state on the Request struct.
> refactor some request code to make the flow simpler & reduce side effects

- fsthttp/handle.go
Closing the response writer signifies to the Compute runtime that the
response has been successfully completed, so we shouldn't defer it in
case the handler panics.
In TinyGo, defers aren't run after panic so this wasn't executed.  In
Go, defers are run.  The result of this was that if a handler panicked
before sending a response, it would send an empty 200 OK response in Go
but a 500 Internal Server Error in TinyGo.
Fixes #98.
> don't defer closing the response writer

- fsthttp/request.go
These methods wrap provided `io.Reader`s that aren't already also closers in our own `nopCloser` type, which we already do in NewRequest.  This extends our ability to send `Content-Length` with certain in-memory types to other uses of requests.
We note in the documentation now that using `SetBody` is preferred over setting the `Body` field directly.)
Fixes #104
> add Request.CloneWithBody and Request.SetBody

- configstore/configstore.go
- integration_tests/config_store/configstore.json
- integration_tests/config_store/main_test.go
- internal/abi/fastly/hostcalls_guest.go
- internal/abi/fastly/hostcalls_noguest.go
- internal/abi/prim/prim.go
Add a `Has` method to the `Dictionary` struct, which will avoid allocations when it's only desired to check if the value exists.
`Has` uses the same host call as `Get`, but gives it an empty buffer. This way it's able to inspect `FastlyStatus` to determine if the value was present, instead of actually copying the value over.
> Add a `Has` method to Dictionary

- integration_tests/config_store/main_test.go
This fixes the "no new variables on left side of :=" while running the config_store integration tests.
> integration_tests/config_store: Fix build errors

- .github/workflows/build-examples.yml
- .github/workflows/integration-tests.yml
- .github/workflows/validate.yml
Actions now runs tests, integration tests, and builds examples on pushes and PRs.
Some of the Go/TinyGo separate actions were consolidated to do both to save time on setup/teardown.
Versions of included actions were bumped.
> GHA: fix up actions, including integration_tests for PRs

- .github/actions/install-tinygo/action.yml
- fsthttp/limits.go
- fsthttp/request.go
- fsthttp/response.go
- internal/abi/fastly/hostcalls_guest.go
- internal/abi/fastly/hostcalls_noguest.go
- internal/abi/fastly/types.go
- internal/abi/prim/prim.go
Closes #101
To enable merging this branch, we verified which of the following hostcalls **fully** support adaptive buffers (return a `buflen` error with a usable value) in both ExecuteD and Viceroy:
ExecuteD:
Viceroy:
Any hostcalls found not to match behavior between ExecuteD and Viceroy will be corrected in Viceroy.
Any hostcalls found not to return a useable value in ExecuteD will be held back in a separate branch until a new version is fully rolled to the fleet.
> Use known and adaptive buffer sizes to lower generated garbage

- fsthttp/request.go
In helping a user troubleshoot the caching behavior of their application, I noticed that it's easy to get the wrong idea from the current documentation that setting `Pass` to `false` prevents a request from ever bypassing the cache. This is not the case; the `Pass` option only has an effect when `true`, and its effect is to force the cache to be bypassed completely. I have edited the docstrings to hopefully make that more clear.
> Clarify the behavior of `Pass` in `CacheOptions`

- fsttest/recorder.go
This should correctly ignore headers set too late to make it into the response.
> fsttest: discard header changes after send

- fsthttp/backend.go
- internal/abi/fastly/types.go
This option looks like it might have been skipped, but can be very handy.
> Expose the ability to turn pooling on or off for dynamic backends.

- fsthttp/response.go
- internal/abi/fastly/hostcalls_noguest.go
- internal/abi/fastly/http_guest.go
> fsthttp, internal: add get_addr_dest_ip/port hostcalls

- fsthttp/request.go
- fsthttp/setparseuri.go
This is like https://github.com/fastly/compute-sdk-go/pull/136 but more suitable for polite company, with less bloat, less opinion about the right way to parse urls, and near zero overhead unless opted in.
The new entry point is behind its own little build tag, fastlyinternalsetparseuri, because it may be needed at different times than the things behind our other private api build tag.
Tested with a real app.
> fsthttp: SetParseRequestURI now lets you register a url parser

- CHANGELOG.md
- _examples/secret-store/main.go
- integration_tests/secret_store/main_test.go
- secretstore/secretstore.go
This consolidates opening the store, getting the secret, and decrypting
the secret into a single call, making more a more convenient API for
getting secrets.
Update the integration test and example to use this, since it does
all the same stuff as before.
> add secretstore.Plaintext convenience function

- cache/core/core.go
Attempting to set request headers in write options for
Transaction.Insert or Transaction.InsertAndStreamBack returns
ErrInvalidArgument.  The docs previously only stated this for
Transaction.Update.
> cache/core: update docs for request headers in transactions

- .github/workflows/integration-tests.yml
- integration_tests/kvstore/main_test.go
- internal/abi/fastly/hostcalls_noguest.go
- internal/abi/fastly/kvstore_guest.go
- internal/abi/fastly/types.go
- kvstore/kvstore.go
This doesn't expose any new API surface but does switch the kvstore backend hostcalls to the v2 API.
> kvstore: switch to kvstore v2 hostcalls

- _examples/print-request/main.go
- fsthttp/request.go
- internal/abi/fastly/hostcalls_noguest.go
- internal/abi/fastly/http_guest.go
Adds a `JA3MD5` field to `fsthttp.TLSInfo` to enable TLS fingerprinting.
This value is available in VCL and the Rust SDK, but was not previously exposed in the Go SDK.
See https://www.fastly.com/blog/the-state-of-tls-fingerprinting-whats-working-what-isnt-and-whats-next for more details
> TLSInfo.JA3MD5 reports the client JA3 signature

- internal/abi/prim/prim.go
Replaces the deprecated `reflect.SliceHeader` with the recommended `unsafe.Slice` and `unsafe.SliceData`, as appropriate.
> internal: remove deprecated reflect.SliceHeader

- .github/workflows/integration-tests.yml
- .github/workflows/validate.yml
- .gitignore
- Makefile
- README.md
- go.mod
- go.sum
- integration_tests/_version/fastly.toml
- integration_tests/_version/main_test.go
- Adds a `Makefile` with tasks for testing across Go and TinyGo.
- Updates the Github Actions workflows to use the make tasks.
- Removes a dependency on `wasmtime`
> Makefile: introduce tasks to aid testing; update CI

- CHANGELOG.md
- go.mod
Due to an abundance of caution, as this release has been implicated in a regression, we are retracting it.
We will continue to investigate and update tests to avoid recurrence.
We encourage any customers who deployed using v1.4.0 to revert to the prior release and re-deploy.
If we re-publish these changes, they will be issued a new version number.
> Retract release v1.4.0

- fsthttp/backend.go
We've gotten various questions over time about the certificate validation behavior. It might not be obvious that:
- Backend certificates are always validated as rooted-at-the-CA...
- ...which consists of a set of default CAs, unless otherwise stated...
- ...but that doesn't include validating the hostname, unless you ask.
Add some doc comments to try to make this behavior more visible. Rust version available internally, JS version [here](https://github.com/fastly/compute-sdk-go/pull/161)
> Add some documentation for CA certificate validation

- cache/core/core.go
- cache/core/core_test.go
Reject ranges where the start position ("from") comes after the end position ("to").
These don't have a good definition of how they should behave; reject them.
> Reject out-of-order ranges

- internal/abi/fastly/configstore_guest.go
The maximum allowed length for a config store entry's value is now configurable. The default is still 8k characters, but may be larger. This changes the Config Store implementation to re-size its buffer when encountering a BUFLEN error and try again.
> Handle config store values larger than 8k

- internal/abi/fastly/httpcache_guest.go
We can't accurately track "origin miss" vs. "pop miss" without knowing
the backend. We want to encourage lookups to be completed (i.e.
transactional lookups) so we can provide accurate CHR metrics.
This function is not exposed outside of internal/, and is not used by
the public API; so, remove it.
> Remove internal non-collapsing lookup

- end_to_end_tests/loopback/main.go
- end_to_end_tests/loopback/main_test.go
- fsthttp/request.go
- internal/abi/fastly/http_guest.go
- internal/abi/fastly/types.go
Fixes a couple crash bugs in the newest host calls.
```
0: In func fastly_http_downstream::downstream_client_ddos_detected at write ddos_detected: Pointer not aligned to 4: Region { start: 4742119, len: 4 }
1: Pointer not aligned to 4: Region { start: 4742119, len: 4 }
```
> New host call bug fixes
